# Generated by Django 5.0.6 on 2024-11-05 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree_structure',
            name='id',
        ),
        migrations.AddField(
            model_name='tree_structure',
            name='binary_bonus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tree_structure',
            name='left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_child', to='placement.tree_structure'),
        ),
        migrations.AddField(
            model_name='tree_structure',
            name='right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_child', to='placement.tree_structure'),
        ),
        migrations.AlterField(
            model_name='tree_structure',
            name='parentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='placement.tree_structure'),
        ),
        migrations.AlterField(
            model_name='tree_structure',
            name='userid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
