# Generated by Django 5.0.6 on 2024-11-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_alter_tree_structure_parentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree_structure',
            name='id',
        ),
        migrations.AlterField(
            model_name='tree_structure',
            name='userid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
