# Generated by Django 5.0.6 on 2024-11-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_remove_tree_structure_id_tree_structure_binary_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree_structure',
            name='binary_bonus',
            field=models.FloatField(default=None),
        ),
    ]
