# Generated by Django 5.0.6 on 2024-11-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_alter_tree_structure_binary_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree_structure',
            name='binary_bonus',
            field=models.FloatField(default=0.0),
        ),
    ]
