# Generated by Django 5.0.6 on 2024-11-04 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_remove_tree_structure_id_alter_tree_structure_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree_structure',
            name='left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_child', to='placement.tree_structure'),
        ),
        migrations.AddField(
            model_name='tree_structure',
            name='right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_child', to='placement.tree_structure'),
        ),
    ]
