# Generated by Django 5.0.6 on 2024-11-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_alter_tree_structure_binary_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree_structure',
            name='matching_bonus',
            field=models.FloatField(default=0.0),
        ),
    ]
