# Generated by Django 5.1.3 on 2024-11-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_tree_structure_matching_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree_structure',
            name='sponsor_bonus',
            field=models.FloatField(default=0.0),
        ),
    ]
