# Generated by Django 5.0.6 on 2024-10-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarytree',
            name='levels',
            field=models.IntegerField(verbose_name='Number of Levels'),
        ),
        migrations.AlterField(
            model_name='binarytree',
            name='total_members',
            field=models.IntegerField(verbose_name='Total Members'),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='binary_bonus_percent',
            field=models.FloatField(verbose_name='Binary Bonus (%)'),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='binary_pairs',
            field=models.IntegerField(verbose_name='Binary Pairs'),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='cap_limit',
            field=models.FloatField(verbose_name='Capping Limit'),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='matching_bonus_levels',
            field=models.IntegerField(verbose_name='Matching Bonus Levels'),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='matching_bonus_percent',
            field=models.FloatField(verbose_name='Matching Bonus (%)'),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='sponsor_bonus_percent',
            field=models.FloatField(verbose_name='Sponsor Bonus (%)'),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='additional_product_price',
            field=models.FloatField(verbose_name='Additional Product Price'),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='base_currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='joining_package_fee',
            field=models.FloatField(verbose_name='Joining Package Fee'),
        ),
    ]
