# Generated by Django 5.0.6 on 2024-10-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm_app', '0002_alter_binarytree_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarytree',
            name='levels',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='binarytree',
            name='total_members',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='binary_bonus_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='binary_pairs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='cap_limit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='matching_bonus_levels',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='matching_bonus_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='sponsor_bonus_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='additional_product_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='joining_package_fee',
            field=models.FloatField(),
        ),
    ]
